### ISSUE TITLE
NullPointerException after Jenkins restart

### ISSUE THREAD

**Issue by flitzie** [AmadeusITGroup/workflow-cps-global-lib-http-plugin#8]
I have noticed an issue with “HTTP Shared Libraries Retriever plugin” https://wiki.jenkins.io/display/JENKINS/HTTP+Shared+Libraries+Retriever+plugin with Jenkins LTS version 2.176.3/4 and 2.190.2.

After each Jenkins restart I get this error for all Jenkins pipeline multi-branch projects:

`
Started by user xxxxxxxxxxxxxxx
Obtained pipeline/Jenkinsfile from bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
Running in Durability level: MAX_SURVIVABILITY
Loading library xxxxxxxxxxxxxx@develop
Attempting to resolve develop from remote references...
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Bitbucket
 > git ls-remote -h -t https://xxxxxxxxxxxxxxxxxxxxxxxxxx.git # timeout=10
Found match: refs/heads/develop revision aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
using credential xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git # timeout=10
Fetching without tags
Fetching upstream changes from https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Bitbucket
 > git fetch --no-tags --progress https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Commit message: "using more SWB logger"
 > git rev-list --no-walk aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa # timeout=10
[Bitbucket] Notifying commit build result
Loading library pipeline-toolbox@7.4.0
java.lang.NullPointerException
        at jenkins.branch.WorkspaceLocatorImpl.getWorkspaceRoot(WorkspaceLocatorImpl.java:274)
        at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:149)
        at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:129)
        at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:125)
        at jenkins.model.Jenkins.getWorkspaceFor(Jenkins.java:2417)
        at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.getDownloadFolder(HttpRetriever.java:272)
        at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.doRetrieve(HttpRetriever.java:189)
        at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.retrieve(HttpRetriever.java:179)
        at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:157)
        at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:138)
        at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:327)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:327)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
`
The only workaround I have found is I have to goto “Manage Jenkins” -> “Configure System” and then press the “apply” button without doing any changes!
I have to repeat this after each Jenkins restart!

Thank you for your help in advance.

**Comment by flitzie** [comment]
I am using the official version 1.2.2 and tested also 1.2.3 "Pipeline: Shared Groovy Libraries through HTTP retrieval".
The Jenkins version is a normal yum installation on RedHat/CentOS (no docker image). Here is the list of plugins I have installed:

ace-editor	1.1	true
additional-metrics	1.3	true
analysis-core	1.96	true
analysis-model-api	7.0.1	true
ansicolor	0.6.2	true
ant	1.10	true
antisamy-markup-formatter	1.6	true
apache-httpcomponents-client-4-api	4.5.10-2.0	true
authentication-tokens	1.3	true
authorize-project	1.3.0	true
badge	1.8	true
basic-branch-build-strategies	1.3.2	true
blueocean	1.19.0	true
blueocean-autofavorite	1.2.4	true
blueocean-bitbucket-pipeline	1.19.0	true
blueocean-commons	1.19.0	true
blueocean-config	1.19.0	true
blueocean-core-js	1.19.0	true
blueocean-dashboard	1.19.0	true
blueocean-display-url	2.3.0	true
blueocean-events	1.19.0	true
blueocean-executor-info	1.19.0	true
blueocean-git-pipeline	1.19.0	true
blueocean-github-pipeline	1.19.0	true
blueocean-i18n	1.19.0	true
blueocean-jira	1.19.0	true
blueocean-jwt	1.19.0	true
blueocean-personalization	1.19.0	true
blueocean-pipeline-api-impl	1.19.0	true
blueocean-pipeline-editor	1.19.0	true
blueocean-pipeline-scm-api	1.19.0	true
blueocean-rest	1.19.0	true
blueocean-rest-impl	1.19.0	true
blueocean-web	1.19.0	true
bouncycastle-api	2.17	true
branch-api	2.5.4	true
build-blocker-plugin	1.7.3	true
build-history-metrics-plugin	1.2	true
build-metrics	1.3	true
build-name-setter	2.0.3	true
build-pipeline-plugin	1.5.8	true
build-timeout	1.19	true
build-user-vars-plugin	1.5	true
cloudbees-bitbucket-branch-source	2.5.0	true
cloudbees-folder	6.9	true
command-launcher	1.3	true
conditional-buildstep	1.3.6	true
config-file-provider	3.6.2	true
configurationslicing	1.47	true
copyartifact	1.43	true
credentials	2.3.0	true
credentials-binding	1.20	true
dashboard-view	2.12	true
dependency-check-jenkins-plugin	5.0.2	true
dependency-track	2.1.0	true
depgraph-view	0.13	true
display-url-api	2.3.2	true
docker-commons	1.15	true
docker-workflow	1.21	true
durable-task	1.33	true
email-ext	2.68	true
envinject	2.3.0	true
envinject-api	1.7	true
extensible-choice-parameter	1.6.0	true
external-monitor-job	1.7	true
favorite	2.3.2	true
findbugs	5.0.0	true
forensics-api	0.5.0	true
generic-webhook-trigger	1.62	true
git	3.12.1	true
git-client	2.9.0	true
git-server	1.8	true
github	1.29.5	true
github-api	1.95	true
github-branch-source	2.5.8	true
global-build-stats	1.5	true
gradle	1.34	true
greenballs	1.15	true
groovy	2.2	true
groovy-postbuild	2.5	true
handlebars	1.1.1	true
handy-uri-templates-2-api	2.1.8-1.0	true
hipchat	2.2.1	true
htmlpublisher	1.21	true
icon-shim	2.0.3	true
ignore-committer-strategy	1.0.4	true
jackson2-api	2.10.0	true
jacoco	3.0.4	true
javadoc	1.5	true
jdk-tool	1.3	true
jenkins-design-language	1.19.0	true
jira	3.0.10	true
job-fan-in	1.1.4	true
job-restrictions	0.8	true
jobConfigHistory	2.24	true
join	1.21	true
jquery	1.12.4-1	true
jquery-detached	1.2.1	true
jquery-ui	1.0.2	true
jsch	0.1.55.1	true
junit	1.28	true
ldap	1.20	true
locale	1.4	true
lockable-resources	2.6	true
logging	1.0.0	true
mailer	1.29	true
mapdb-api	1.0.9.0	true
mashup-portlets-plugin	1.1.0	true
matrix-auth	2.5	true
matrix-project	1.14	true
maven-plugin	3.4	true
mercurial	2.8	true
mission-control-view	0.9.15	true
momentjs	1.1.1	true
monitoring	1.79.0	true
multiple-scms	0.6	true
nested-view	1.17	true
pam-auth	1.6	true
parameterized-trigger	2.35.2	true
pipeline-aggregator-view	1.8	true
pipeline-build-step	2.9	true
pipeline-github-lib	1.0	true
pipeline-graph-analysis	1.10	true
pipeline-input-step	2.11	true
pipeline-milestone-step	1.3.1	true
pipeline-model-api	1.3.9	true
pipeline-model-declarative-agent	1.1.1	true
pipeline-model-definition	1.3.9	true
pipeline-model-extensions	1.3.9	true
pipeline-rest-api	2.12	true
pipeline-stage-step	2.3	true
pipeline-stage-tags-metadata	1.3.9	true
pipeline-stage-view	2.12	true
pipeline-utility-steps	2.3.1	true
plain-credentials	1.5	true
promoted-builds	3.4	true
pubsub-light	1.13	true
rebuild	1.31	true
release	2.10.2	true
resource-disposer	0.14	true
run-condition	1.2	true
saferestart	0.3	true
scm-api	2.6.3	true
script-security	1.66	true
sse-gateway	1.20	true
ssh-credentials	1.18	true
ssh-slaves	1.31.0	true
structs	1.20	true
subversion	2.12.2	true
tasks	4.53	true
thinBackup	1.9	true
timestamper	1.10	true
token-macro	2.10	true
trilead-api	1.0.5	true
variant	1.3	true
warnings	5.0.1	true
warnings-ng	7.1.0	true
windows-slaves	1.5	true
workflow-aggregator	2.6	true
workflow-api	2.37	true
workflow-basic-steps	2.18	true
workflow-cps	2.74	true
workflow-cps-global-lib	2.15	true
workflow-cps-global-lib-http	1.2.3	true
workflow-durable-task-step	2.34	true
workflow-job	2.35	true
workflow-multibranch	2.21	true
workflow-scm-step	2.9	true
workflow-step-api	2.20	true
workflow-support	3.3	true
ws-cleanup	0.37	true

**Comment by fabricepipart1a** [comment]
I think I manage to reproduce the same issue with a simple ```mvn hpi:run```
```
Started by user unknown or anonymous
Running in Durability level: MAX_SURVIVABILITY
Loading library ecommerce-library@17.1.0
java.io.IOException: Jenkins may be offline
	at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.getSlave(HttpRetriever.java:355)
	at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.doRetrieve(HttpRetriever.java:214)
	at com.amadeus.jenkins.plugins.workflow.libs.HttpRetriever.retrieve(HttpRetriever.java:203)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:156)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:137)
	at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:123)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:516)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:479)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

Note that it is with Jenkins 2.121 and that, the problem disappears as soon as I save my Admin config... weird...

**Comment by fabricepipart1a** [comment]
I think I got it. For code _beauty_ I had stored the Node that corresponds to our executor. It looks like a bad idea! Doing so, I store the wrong instance.
If I rerun `Jenkins.get()` at the last moment, it gives me the right instance which will probably avoid the issue.

**Comment by fabricepipart1a** [comment]
It seems to work. Expect the fix in the next release. I'll try to release it ASAP!

**Comment by fabricepipart1a** [comment]
1.4.2 is the recommended version to use for your issue
